preserve_hierarchy: true

files:
  - source: /src/data/en_US/ships.json
    translation: /src/data/%locale_with_underscore%/ships.json
  - source: /src/data/en_US/item.json
    translation: /src/data/%locale_with_underscore%/item.json
  - source: /src/data/en_US/commodities.json
    translation: /src/data/%locale_with_underscore%/commodities.json
  - source: /src/data/en_US/cosmetics.json
    translation: /src/data/%locale_with_underscore%/cosmetics.json
  - source: /src/data/en_US/calendar.json
    translation: /src/data/%locale_with_underscore%/calendar.json
  - source: /src/data/en_US/factions.json
    translation: /src/data/%locale_with_underscore%/factions.json
  - source: /src/data/en_US/locations.json
    translation: /src/data/%locale_with_underscore%/locations.json
  - source: /src/data/en_US/materials.json
    translation: /src/data/%locale_with_underscore%/materials.json
  - source: /src/data/en_US/modifications.json
    translation: /src/data/%locale_with_underscore%/modifications.json
  - source: /src/data/en_US/perks.json
    translation: /src/data/%locale_with_underscore%/perks.json
  - source: /src/data/en_US/seasons.json
    translation: /src/data/%locale_with_underscore%/seasons.json
  - source: /src/data/en_US/ultimates.json
    translation: /src/data/%locale_with_underscore%/ultimates.json
  - source: /src/data/en_US/empireSkills.json
    translation: /src/data/%locale_with_underscore%/empireSkills.json
  - source: /src/data/en_US/worldEvents.json
    translation: /src/data/%locale_with_underscore%/worldEvents.json
  - source: /src/data/en_US/mapLocations.json
    translation: /src/data/%locale_with_underscore%/mapLocations.json
  - source: /src/data/en_US/sets.json
    translation: /src/data/%locale_with_underscore%/sets.json
  - source: /src/data/en_US/npcs.json
    translation: /src/data/%locale_with_underscore%/npcs.json
