name: Crowdin Action

on:
  push:
    branches: [ main ]
  schedule:
    # 每周运行（UTC）
    - cron: '0 0 * * 1'

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # by https://github.com/crowdin/github-action
      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          config: './crowdin.yml'
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: l18n_crowdin_translations
          create_pull_request: true
          pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
